packages:
  - examples/*
  - packages/*
  - packages/schema/backends/*
  - packages/exchange/wire
  - packages/exchange/transports/*
  - packages/exchange/stores/*
  - tests/*

onlyBuiltDependencies:
  - classic-level
  - esbuild