packages:
  - examples/*
  - packages/*
  - packages/schema/backends/*
  - packages/exchange/wire
  - packages/exchange/network-adapters/*
  - packages/exchange/storage-adapters/*
  - tests/*

onlyBuiltDependencies:
  - classic-level
  - esbuild