/**
 * Kyneta Runtime
 *
 * The runtime provides the functions that compiled Kyneta code calls
 * to manage DOM updates, subscriptions, and cleanup.
 *
 * ## Import Paths
 *
 * **For compiled code** (generated by the Kyneta compiler):
 * ```typescript
 * import { subscribe, listRegion, conditionalRegion } from "@kyneta/cast/runtime"
 * ```
 *
 * **For tests** (reset functions, subscription tracking):
 * ```typescript
 * import { resetScopeIdCounter, activeSubscriptions } from "@kyneta/cast/testing"
 * ```
 *
 * @packageDocumentation
 */

// =============================================================================
// Public API
// =============================================================================

export { getRootScope, mount, rootScope } from "./mount.js"
export { Scope } from "./scope.js"

// =============================================================================
// Compiler Runtime API (for generated code)
// =============================================================================

export {
  conditionalRegion,
  filteredListRegion,
  listRegion,
  planFilterUpdate,
} from "./regions.js"
export {
  read,
  type SubscriptionId,
  subscribe,
  unsubscribe,
  valueRegion,
} from "./subscribe.js"

export { inputTextRegion, textRegion } from "./text-patch.js"

// =============================================================================
// Runtime version
// =============================================================================

export const RUNTIME_VERSION = "0.0.1"
