/**
 * Kinetic Runtime
 *
 * The runtime provides the functions that compiled Kinetic code calls
 * to manage DOM updates, subscriptions, and cleanup.
 *
 * ## Import Paths
 *
 * **For compiled code** (generated by the Kinetic compiler):
 * ```typescript
 * import { subscribe, listRegion, conditionalRegion } from "@loro-extended/kinetic/runtime"
 * ```
 *
 * Note: Loro-specific bindings (bindTextValue, bindChecked, etc.)
 * are exported from "@loro-extended/kinetic/loro" instead, to maintain
 * a clean separation between Loro-agnostic runtime and Loro-specific features.
 *
 * @packageDocumentation
 */

// =============================================================================
// Public API
// =============================================================================

export { getRootScope, mount, rootScope } from "./mount.js"
export { __resetScopeIdCounter, Scope } from "./scope.js"

// =============================================================================
// Compiler Runtime API (for generated code)
// =============================================================================

export {
  __subscribe as subscribe,
  __subscribeMultiple as subscribeMultiple,
  __subscribeWithValue as subscribeWithValue,
  __unsubscribe as unsubscribe,
  type SubscriptionId,
} from "./subscribe.js"

export {
  __listRegion as listRegion,
  __conditionalRegion as conditionalRegion,
} from "./regions.js"

// =============================================================================
// Testing Utilities (internal, not for generated code)
// =============================================================================

export {
  __activeSubscriptions,
  __getActiveSubscriptionCount,
  __resetSubscriptionIdCounter,
} from "./subscribe.js"

// =============================================================================
// Runtime version
// =============================================================================

export const RUNTIME_VERSION = "0.0.1"
