/**
 * Kinetic Runtime
 *
 * The runtime provides the functions that compiled Kinetic code calls
 * to manage DOM updates, subscriptions, and cleanup.
 *
 * ## Import Paths
 *
 * **For compiled code** (generated by the Kinetic compiler):
 * ```typescript
 * import { subscribe, listRegion, conditionalRegion } from "@loro-extended/kinetic/runtime"
 * ```
 *
 * **For tests** (reset functions, subscription tracking):
 * ```typescript
 * import { resetScopeIdCounter, activeSubscriptions } from "@loro-extended/kinetic/testing"
 * ```
 *
 * Note: Loro-specific bindings (bindTextValue, bindChecked, etc.)
 * are exported from "@loro-extended/kinetic/loro" instead, to maintain
 * a clean separation between Loro-agnostic runtime and Loro-specific features.
 *
 * @packageDocumentation
 */

// =============================================================================
// Public API
// =============================================================================

export { getRootScope, mount, rootScope } from "./mount.js"
export { Scope } from "./scope.js"

// =============================================================================
// Compiler Runtime API (for generated code)
// =============================================================================

export {
  subscribe,
  subscribeMultiple,
  subscribeWithValue,
  unsubscribe,
  type SubscriptionId,
} from "./subscribe.js"

export { listRegion, conditionalRegion } from "./regions.js"

export { textRegion } from "./text-patch.js"

// =============================================================================
// Runtime version
// =============================================================================

export const RUNTIME_VERSION = "0.0.1"
